
package views;

import components.Airplane;
import java.awt.Font;
import javax.swing.JLabel;


public class GamePanel extends javax.swing.JPanel {

    private Airplane plane;
    private JLabel lifePlane;

    /**
     * Creates new form GamePanel
     */
    public GamePanel() {
        initComponents();
        this.setLayout(null);
    }

    public void setPlane(Airplane plane){
        this.plane=plane;
        this.add(this.plane);
        this.revalidate();
        this.repaint();
    }
    
    public Airplane getPlane() {
        return plane;
    }
    
    public void setLifePlane(short life) {
        this.lifePlane = new JLabel("Life: " + life);
        Font font = new Font(Font.SANS_SERIF,Font.BOLD, 20);
        this.lifePlane.setFont(font);
        this.lifePlane.setBounds(0,0,100,100);
        this.add(this.lifePlane);
        this.revalidate();
        this.repaint();
    }
    
    public void changeLife(short life) {
        if (life < 0) {
            life = 0;
        }
        this.lifePlane.setText("Life: " + life);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 693, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
